//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHorizonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidList
    {
        public int BidId { get; set; }
        public int JobId { get; set; }
        public int BidBy { get; set; }
        public string Description { get; set; }
        public List<Links> Links = new List<Links>();
    
        public virtual JobList JobList { get; set; }
        public virtual User User { get; set; }
    }
}
