//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHorizonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public int ForumId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Comment1 { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual User User { get; set; }
    }
}
