//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHorizonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messege
    {
        public int MessegeId { get; set; }
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public string Messege1 { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
