//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHorizonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BidLists = new HashSet<BidList>();
            this.Comments = new HashSet<Comment>();
            this.Files = new HashSet<File>();
            this.Fora = new HashSet<Forum>();
            this.JobHistories = new HashSet<JobHistory>();
            this.JobLists = new HashSet<JobList>();
            this.Messeges = new HashSet<Messege>();
            this.Messeges1 = new HashSet<Messege>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Type { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Account_Status { get; set; }
        public string Address { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<double> Rating { get; set; }
        public string WorkType { get; set; }
        public List<Links> Links = new List<Links>();

        public virtual ICollection<BidList> BidLists { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<Forum> Fora { get; set; }
        public virtual ICollection<JobHistory> JobHistories { get; set; }
        public virtual ICollection<JobList> JobLists { get; set; }
        public virtual ICollection<Messege> Messeges { get; set; }
        public virtual ICollection<Messege> Messeges1 { get; set; }
    }
}
